mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #polls
    url(r'^polls/', include('polls.urls', namespace="polls")),
)

mysite/polls/urls.py
#! /usr/bin/env python
#coding=utf-8
from django.conf.urls import patterns, include, url

from polls import views

#urlpatterns = patterns('',
#    # ex: /polls/
#    url(r'^$', views.index, name='index'),
#    # ex: /polls/5/
#    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
#    # ex: /polls/5/results/
#    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
#    # ex: /polls/5/vote/
#    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
#)

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/polls/models.py
#! /usr/bin/env python
#coding=utf-8
import datetime
from django.db import models

# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.shor_description = '最近发布？'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

mysite/polls/views.py
#! /usr/bin/env python
#coding=utf-8

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        return Poll.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'poll' : p,
            'error_message' : "你未选择任何选项！",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # args p.id后面为什么要加','?
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>投票系统</title>

    <script type="text/javascript" src="{% static 'polls/jquery/jquery-2.0.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/bootstrap/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'polls/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'polls/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'polls/basic/css/style.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="row-fluid">
        <div class="hero-unit">
            <h1>欢迎参加投票系统</h1>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}

<ul class="breadcrumb">
    <li><a href="{% url 'polls:index' %}">首页</a> <span class="divider">/</span></li>
    <li><a href="{% url 'polls:index' %}">所有投票</a> <span class="divider">/</span></li>
    <li class="active">{{ poll.question }}</li>
</ul>

<div class="span3"></div>
<div class="span5">
    <h1>问题：{{ poll.question }}</h1>

    {% if error_message %}<p class="label label-important"><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <label class="radio" for="choice{{ forloop.counter }}">
            <input  type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            {{ choice.choice_text }}
        </label>
    {% endfor %}
    <input class="btn btn-success" type="submit" value="投票" />
    <a href="{% url 'polls:index' %}">返回所有投票</a>
    </form>
</div>

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
        <ul class="breadcrumb">
          <li><a href="{% url 'polls:index' %}">首页</a> <span class="divider">/</span></li>
        </ul>

        {% if latest_poll_list %}
        <div class="index-votes">
            {% for poll in latest_poll_list %}
                <div class="vote">
                    <i class="icon-search"></i>
                    <p class="label label-success">
                        {{ poll.question }}
                    </p>
                    <br />
                    <p>发布日期：{{ poll.pub_date }}</p>
                    <a class="btn" href="{% url 'polls:detail' poll.id %}"><i class="icon-thumbs-up"></i></a>
                </div>
            {% endfor %}
        </div>
        {% else %}
            <p>无投票。</p>
        {% endif %}
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}

<ul class="breadcrumb">
    <li><a href="{% url 'polls:index' %}">首页</a> <span class="divider">/</span></li>
    <li><a href="{% url 'polls:index' %}">所有投票</a> <span class="divider">/</span></li>
    <li class="active">{{ poll.question }}</li>
</ul>

<div class="span3"></div>
<div class="span5">

    <h1>{{ poll.question }}</h1>

    <ul>
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} 票 </li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' poll.id %}">再次投票?</a>
    <br />
    <a href="{% url 'polls:index' %}">返回所有投票</a>
</div>
{% endblock %}